/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/newVinyl.glb 
*/

import React, { useContext } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";

export function NewVinyl(props) {
  const { nodes, materials } = useGLTF("/newVinyl.glb");

  const { position, scale } = useControls({
    position: [-0.2, 0.1, 0.4],
    scale: [0.88, 6.1, 0.88],
  });

  return (
    <group {...props} position={[-0.23, 0.06, 0.4]} dispose={null}>
      <group scale={scale}>
        <mesh
          geometry={nodes.Cylinder002.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cylinder002_1.geometry}
          material={materials.vinyl}
        />
        <mesh
          geometry={nodes.Cylinder002_2.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Cylinder002_3.geometry}
          material={materials["Text.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/newVinyl.glb");
