/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/tableAndDisk.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const TableAndRecord = React.forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/tableAndDisk.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.21, 0.06, 0.39]}
        scale={0.88}
        name="record"
        ref={ref}
      >
        <mesh geometry={nodes.Mesh.geometry} material={materials.Record} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.Label} />
        <mesh
          geometry={nodes.Text021.geometry}
          material={materials.Record}
          position={[0, 0.01, -0.1]}
          scale={0.54}
        />
        <mesh
          geometry={nodes.Text024.geometry}
          material={materials.Record}
          position={[-0.2, 0.01, 0.1]}
        />
      </group>

      <mesh
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.tABLE}
        scale={3}
        position={[0, -0.39, 0]}
        name="Table"
      />
    </group>
  );
});

useGLTF.preload("/tableAndDisk.glb");

export default TableAndRecord;
